import { Product } from './models/productModel'

export const sampleProducts: Product[] = [
  {
    dinoName: 'Indominus rex',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/7/72/Indominus_JWE2_Profile.png/revision/latest?cb=20220602000806',
    rarity: 'Legendary',
    type: 'Dinosaurs',
    price: 2516000,
    description:
      'Indominus rex is an incredibly aggressive and intelligent carnivore, with an extremely high intolerance for deviations from its comfort levels. Even in comparison to other large carnivores such as Tyrannosaurus, Indominus is an asocial animal which does not tolerate other members of its species in its enclosure (unless, however, Group Adaptation genes are applied before incubation). ',
    era: 'Holocene',
    family: 'Hybrid',
    diet: 'Carnivore',
    attack: 116,
    defense: 34,
    appeal: 1850,
    likes: ['Velociraptor'],
    dislikes: [
      'Small Herbivores',
      'Medium Herbivores',
      'Sauropods',
      'Carnivores',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Velociraptor',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/b/bd/Velociraptor_JWE2_Profile.png/revision/latest?cb=20220602000845',
    rarity: 'Super Rare',
    type: 'Dinosaurs',
    price: 1450000,
    description:
      'Velociraptors will engage in death duels with all other small carnivores such as Dilophosaurus and Proceratosaurus, as well as pachycephalosaurids such as Stygimoloch, when encountered. They will engage in territorial fights with other Velociraptors in packs of 6 or in death duels in packs greater than 6. It will also engage in predation against all ornithopod dinosaurs such as Dryosaurus and Tsintaosaurus.',
    era: 'Late Cretaceous',
    family: 'Dromaeosauridae',
    diet: 'Carnivore',
    attack: 45,
    defense: 18,
    appeal: 185,
    likes: ['Scavenger', 'Indominus rex'],
    dislikes: ['Carnivore', 'Indoraptor', 'Therizinosaurus'],
  },
  {
    dinoName: 'Therizinosaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/6/68/Therizinosaurus_JWE2_Profile.png/revision/latest?cb=20230813020553',
    rarity: 'Super Rare',
    type: 'Dinosaurs',
    price: 1073125,
    description:
      'Therizinosaurus is a genus of therizinosaurid dinosaur . Originating from Late Cretaceous Asia, it is recognizable via its large scythe-like claws.',
    era: 'Late Cretaceous',
    family: 'Therizinosauridae',
    diet: 'Herbivore',
    attack: 98,
    defense: 24,
    appeal: 1222,
    likes: ['Scavenger'],
    dislikes: ['Everything'],
  },
  {
    dinoName: 'Amargasaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/d/df/Amargasaurus_JWE2_Profile.png/revision/latest?cb=20220601223414',
    rarity: 'Rare',
    type: 'Dinosaurs',
    price: 150000,
    description:
      'Named after the site of its discovery, La Amarga Formation in Argentina, Amargasaurus is a sauropod of relatively small size, measuring around 10 meters in length and weighing around 2.9 tons. A member of the Dicraeosauridae family of sauropod dinosaurs, its long neck and sharp teeth allow it to eat tough vegetation from trees, while the two rows of long neural spines that run along its neck and upper back - forming a double row - help Amargasaurus to defend itself from predators',
    era: 'Early Cretaceous',
    family: 'Dicraeosauridae',
    diet: 'Herbivore',
    attack: 48,
    defense: 36,
    appeal: 77,
    likes: [
      'Ornithomimosaurid',
      'Ceratopsid',
      'Ankylosaurid',
      'Pachycephalosaurid',
    ],
    dislikes: ['Sauropod', 'Indominus rex', 'Scorpios rex'],
  },
  {
    dinoName: 'Scorpios rex',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/6/62/Scorpios_JWE2_Profile.png/revision/latest?cb=20220602001324',
    rarity: 'Super Rare',
    type: 'Dinosaurs',
    price: 1085000,
    description:
      'Scorpios rex is a hybrid dinosaur shares many similarities with the much later Indoraptor, though with a much shorter snout, prominent spikes, rows of serrated, jagged, uneven teeth designed to tear through the flesh of its prey characterize this impressive species as an intimidating apex carnivore. It has blood-red eyes, charcoal-black scales, and a yellow belly. Along with DNA from a variety of carnivorous dinosaurs, a series of venomous quills also decorate its head and tail, acquired from the use of splicing the DNA of the scorpionfish, a deadly fish that secretes venom from its fins.',
    era: 'Holocene',
    family: 'Hybrid',
    diet: 'Carnivore',
    attack: 87,
    defense: 36,
    appeal: 101,
    likes: ['Nothing'],
    dislikes: ['Everything'],
  },
  {
    dinoName: 'Coelophysis',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/4/42/Coelophysis_JWE2_Profile.png/revision/latest?cb=20220602225325',
    rarity: 'Common',
    type: 'Dinosaurs',
    price: 50000,
    description:
      'Among the earliest dinosaurs to have walked the earth, Coelophysis was a small theropod dinosaur that thrived approximately 190 to 225 million years ago in what is now Africa and North America. With a length of about three meters and a weight ranging from 18 to 23 kilograms, its name translates to "Hollow Form" in reference to its hollow leg bones, which allow it to reach speeds of up to 25mph thanks to its light frame. It boasted a slender and agile build, embodying the characteristics of a nimble predator.',
    era: 'Late Triassic',
    family: 'Coelophysidae',
    diet: 'Carnivore',
    attack: 15,
    defense: 8,
    appeal: 21,
    likes: ['Everything'],
    dislikes: ['Indominus rex', 'Indoraptor', 'Scorpios rex'],
  },
  {
    dinoName: 'Indoraptor',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/7/77/Indoraptor_JWE2_Profile.png/revision/latest?cb=20220602000614',
    rarity: 'Legendary',
    type: 'Dinosaurs',
    price: 2750000,
    description:
      'Indoraptor is an extremely aggressive hybrid. It will try to escape like other dinosaurs, but will kill many more guests. It can not coexist with others of its own kind (unless specific social genes are applied to it prior to incubation) and it will kill almost anything up to the size of a Spinosaurus. Its behaviour is reminiscent to that of Indominus rex and Velociraptor. It will fight with most dinosaurs it is enclosed with, including far larger carnivores such as Tyrannosaurus. However, Indoraptor will not attack large sauropods such as Apatosaurus and Brachiosaurus, and can therefore be exhibited with them.',
    era: 'Holocene',
    family: 'Hybrid',
    diet: 'Carnivore',
    attack: 92,
    defense: 45,
    appeal: 1850,
    likes: ['None'],
    dislikes: [
      'Ornithomimosaurid',
      'Ceratopsid',
      'Ankylosaurid',
      'Sauropod',
      'Velociraptor',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Pachyrhinosaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/5/58/Pachyrhinosaurus_JWE2_Profile.png/revision/latest?cb=20220613214647',
    rarity: 'Common',
    type: 'Dinosaurs',
    price: 75000,
    description:
      'Measuring around 6 meters in length and weighing as much as 3 tons, Pachyrhinosaurus is a herbivorous dinosaur from the ceratopsid family, with strong teeth in its cheeks for breaking down tough vegetation. Its name translates to "Thick-Nosed Lizard", referring the unusual blunt shape of its snout – while this genus is identifiable by the array of adornments on its skull, including a frill and horns. Rather than nasal or brow horns typically seen in other ceratopsians, Pachyrhinosaurus bares a massive, thick, flattened bone on their heads, commonly referred to as a "nasal boss", with a large one over the nose and another smaller one over the eyes.',
    era: 'Late Cretaceous',
    family: 'Ceratopsidae',
    diet: 'Herbivore',
    attack: 60,
    defense: 30,
    appeal: 101,
    likes: ['Ornithomimosaurid', 'Ceratopsid', 'Ankylosaurid', 'Hadrosaurid'],
    dislikes: ['Torosaurus', 'Sinoceratops', 'Stegosaurid', 'Therizinosaurus'],
  },
  {
    dinoName: 'Torosaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/5/55/Torosaurus_JWE2_Profile.png/revision/latest?cb=20220613222434',
    rarity: 'Rare',
    type: 'Dinosaurs',
    price: 220000,
    description:
      'Among the larger ceratopsians and notable for having one of the largest skulls the world has ever seen, measuring up to 3 meters in length, Torosaurus is a herbivorous ceratopsid dinosaur that lived across the western interior of North America. Torosaurus has a large bulky body, a wide, sweeping frill, and three horns; one on its snout and two above its eyes. Similar in size and appearance to its relative, Triceratops, Torosaurus measures nearly 8 meters in length and weighs up to 6 tons, requiring a huge amount of vegetation every day for sustenance. Its beak and shearing teeth allowed it to eat tough vegetation like palms and horsetails.',
    era: 'Late Cretaceous',
    family: 'Ceratopsidae',
    diet: 'Herbivore',
    attack: 58,
    defense: 36,
    appeal: 74,
    likes: [
      'Ornithomimosaurid',
      'Ceratopsid',
      'Ankylosaurid',
      'Hadrosaurid',
      'Scavenger',
    ],
    dislikes: [
      'Triceratops',
      'Styracosaurus',
      'Sinoceratops',
      'Pachyrhinosaurus',
      'Carnivores',
      'Stegosaurid',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Sinoceratops',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/f/f0/Sinoceratops_JWE2_Profile.png/revision/latest?cb=20220613214849',
    rarity: 'Rare',
    type: 'Dinosaurs',
    price: 140000,
    description:
      'A relatively large ceratopsian that existed in China around 73 million years ago and easily identifiable thanks to the large horn on its snout, Sinoceratops is similar in size to relatives such as Chasmosaurus, measuring up to over 8 meters in length and weigh as much as 2 to 4 tons. Its name translates to "Chinese Horned Face". Significant as the first known ceratopsid found outside of North America, Sinoceratops has a short, pudgy body; a short, hooked rhino-like horn on its nose; no horns above its eyes; and a short, round, curved neck frill with a crown-like appearance formed by forward-curving hornlets.',
    era: 'Late Cretaceous',
    family: 'Ceratopsidae',
    diet: 'Herbivore',
    attack: 56,
    defense: 34,
    appeal: 110,
    likes: [
      'Ornithomimosaurid',
      'Ceratopsid',
      'Ankylosaurid',
      'Hadrosaurid',
      'Scavenger',
    ],
    dislikes: [
      'Triceratops',
      'Styracosaurus',
      'Torosaurus',
      'Pachyrhinosaurus',
      'Carnivores',
      'Stegosaurid',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Triceratops',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/8/85/Triceratops_JWE2_Profile.png/revision/latest?cb=20220613222443',
    rarity: 'Common',
    type: 'Dinosaurs',
    price: 175000,
    description:
      'Among the largest of the ceratopsian family, the large bony neck frill and three horns on its head – which give rise to its name translating to "Three-Horned Face" – serve to make Triceratops one of the most famous dinosaurs in the world, and this makes it a popular attraction. Similar in size to its relatives Pentaceratops and Torosaurus, Triceratops measures between 9 and 10 meters long and weighs well over 8 tons.Triceratops is a herbivore, with its diet consisting mainly of ground level vegetation, although their size may have enabled them to knock over larger plants and trees to feed on.',
    era: 'Late Cretaceous',
    family: 'Ceratopsidae',
    diet: 'Carnivore',
    attack: 76,
    defense: 38,
    appeal: 108,
    likes: [
      'Ornithomimosaurid',
      'Ceratopsid',
      'Ankylosaurid',
      'Hadrosaurid',
      'Scavenger',
    ],
    dislikes: [
      'Styracosaurus',
      'Torosaurus',
      'Sinoceratops',
      'Carnivores',
      'Stegosaurid',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Pteranodon',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/2/2a/Pteranodon_database_image_from_Evolution_2.png/revision/latest?cb=20211209152805',
    rarity: 'Super Rare',
    type: 'Flying reptiles',
    price: 310000,
    description:
      'One of the largest pterosaurs ever to have existed with a wingspan stretching up to over 7 meters, Pteranodon is a genus of Late Cretaceous pterosaur easily recognizable thanks to the crest on the top of its skull, which it uses for display purposes. Although its diet consists largely of fish, Pteranodon does not have teeth, chewing its prey with its beak – in fact, its name is derived from Greek meaning "Toothless Wing". These pterosaurs are extremely light and delicate in order to be able to fly. It is likely that Pteranodon was a coastal animal that roosted offshore, out of reach of predators. Their toothless jaws with a pouch of skin could hold fish, like modern pelicans, and the crest that could have acted as a counterbalance when skimming the water surface.',
    era: 'Late Cretaceous',
    family: 'Pteranodontidae',
    diet: 'Piscivore',
    attack: 60,
    defense: 30,
    appeal: 101,
    likes: ['Geosternbergia'],
    dislikes: ['Indoraptor'],
  },
  {
    dinoName: 'Geosternbergia',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/5/5d/Geosternbergia_database_image_from_Evolution_2.png/revision/latest?cb=20211209152729',
    rarity: 'Rare',
    type: 'Flying reptiles',
    price: 125000,
    description:
      'Geosternbergia is a very large pterosaur, one of the largest with a massive wingspan of over seven meters. It possesses a long, tapered beak that can grab fish out of the water or be used as a spear for catching them. However, Geosternbergia lacked any teeth and fed on fish and other small marine life. In addition, similar to Pteranodon, Geosternbergia is notable for the large, distinctive crest on its head found on male individuals with the females possessed a smaller crest.',
    era: 'Late Cretaceous',
    family: 'Pteranodontidae',
    diet: 'Piscivore',
    attack: 55,
    defense: 30,
    appeal: 125,
    likes: ['Pteranodon', 'Tropeognathus'],
    dislikes: ['None'],
  },
  {
    dinoName: 'Plesiosaurus',
    image:
      'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiIyMDIxLTEwL3BsZXNpb3NhdXJ1cy5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjMwMH19fQ==',
    rarity: 'Common',
    type: 'Marine reptiles',
    price: 100000,
    description:
      'Known for its powerful paddle-like limbs that allow it to swim through water at speed and a flexible, elongated neck that can move quickly to catch fish and other prey, Plesiosaurus is a piscivorous marine reptile that measures 3.5 meters in length. The namesake of the plesiosaur family, its name translates to "Near Lizard". Although small compared to other members of its family, such as Elasmosaurus, Plesiosaurus was the very first plesiosaur ever discovered and dates back to the Early Jurassic period around 200 million years ago,',
    era: 'Early Jurassic',
    family: 'Plesiosauridae',
    diet: 'Piscivore',
    attack: 27,
    defense: 12,
    appeal: 238,
    likes: ['None'],
    dislikes: ['None'],
  },
  {
    dinoName: 'Attenborosaurus',
    image:
      'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiIyMDIxLTExL2F0dGVuYm9yb3NhdXJ1c18xNTc3NTEucG5nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo0MDB9fX0=',
    rarity: 'Super Rare',
    type: 'Marine reptiles',
    price: 595000,
    description:
      'Named after esteemed British natural historian David Attenborough, Attenborosaurus was a medium-sized pliosaur, reaching more than 6 meters in length and weighing a ton. It is notable for its long neck and paddle-like limbs, both of which allow this piscivorous marine reptile to move through water at high speeds and catch prey with its long, sharp teeth. Skin impressions found on its bones suggest that it may have had membranous skin, possibly to reduce water resistance.',
    era: 'Early Jurassic',
    family: 'Pliosauridae',
    diet: 'Piscivore',
    attack: 67,
    defense: 18,
    appeal: 860,
    likes: ['Marine (Medium)'],
    dislikes: ['None'],
  },
  {
    dinoName: 'Tyrannosaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/d/da/Tyrannosaurus_JWE2_Profile.png/revision/latest?cb=20230813015206',
    rarity: 'Legendary',
    type: 'Dinosaurs',
    price: 1980000,
    description:
      'The most famous of all dinosaurs in history and among the largest theropod dinosaurs of all time, measuring at around 14.5 meters in length and over eight tons in weight, Tyrannosaurus is a species of tyrannosaurid dinosaur from the Late Cretaceous Period. The apex predator of its time, it lived throughout western North America at the end of the Cretaceous period alongside other dinosaurs such as the ceratopsians Triceratops and Torosaurus, the hadrosaur Edmontosaurus, the armored Ankylosaurus, the pachycephalosaurs Pachycephalosaurus, Stygimoloch and Dracorex, the smaller theropod Troodon, and the ornithomimid Struthiomimus, making it one of the latest species of non-avian dinosaurs to evolve prior to the great extinction 66 million years ago. Tyrannosaurus enjoys a fearsome reputation around the world thanks to its size, power and aggression – a status borne out by its name, which translates to "King of the Tyrant Lizards" – and to many, it represents the ultimate predator.',
    era: 'Late Cretaceous',
    family: 'Tyrannosauridae',
    diet: 'Carnivore',
    attack: 120,
    defense: 65,
    appeal: 1890,
    likes: ['Scavenger'],
    dislikes: ['Carnivores', 'Therizinosaurus'],
  },
  {
    dinoName: 'Styracosaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/9/96/Styracosaurus_JWE2_Profile.png/revision/latest?cb=20220613222419',
    rarity: 'Rare',
    type: 'Dinosaurs',
    price: 100000,
    description:
      'Measuring over 5 meters in length and weighing almost 2 tons, Styracosaurus is a medium to large-sized ceratopsian dinosaur that lived in the Late Cretaceous period in what is now North America with distinctive, lengthy horns protruding from its large neck frill and single horn protruding from its snout. Its name translates into "Spiked Lizard". They are believed to have lived in herds, and travelled in large groups for protection and foraging for food. Its tough beak and shearing cheek teeth would have been ideal for slicing up plant matter. The dinosaur base cosmetic genome is a lightish-brown, with dark green spots along its back with a hint of orange on the frill.',
    era: 'Late Cretaceous',
    family: 'Ceratopsidae',
    diet: 'Herbivore',
    attack: 40,
    defense: 19,
    appeal: 62,
    likes: ['Ornithomimosaurid', 'Ceratopsid', 'Ankylosaurid', 'Hadrosaurid'],
    dislikes: [
      'Triceratops',
      'Torosaurus',
      'Sinoceratops',
      'Stegosaurid',
      'Therizinosaurus',
    ],
  },
  {
    dinoName: 'Barbaridactylus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/c/c6/Barbaridactylus_database_image_from_Evolution_2.png/revision/latest?cb=20220915184041',
    rarity: 'Common',
    type: 'Flying reptiles',
    price: 95000,
    description:
      'With its incredibly distinctive head crest, Barbaridactylus is a medium-sized pterosaur that lived towards the end of the Late Cretaceous period, around 72-66 million years ago. This genus is distinct from most other pterosaurs in that it is part of the nyctosaurid family, which rarely walked on land and was specially adapted for almost constant flight. This flying hunter takes its name from the Barbary Coast of North Africa, near to where Barbaridactylus was discovered.',
    era: 'Late Cretaceous',
    family: 'Nyctosauridae',
    diet: 'Piscivore',
    attack: 42,
    defense: 20,
    appeal: 195,
    likes: ['Quetzalcoatlus'],
    dislikes: ['Therizinosaurus'],
  },
  {
    dinoName: 'Tropeognathus',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/5/5d/Tropeognathus_database_image_from_Evolution_2.png/revision/latest?cb=20211209152811',
    rarity: 'Super Rare',
    type: 'Flying reptiles',
    price: 450000,
    description:
      'Tropeognathus is a piscivorous pterosaur that lived in South America during the Early Cretaceous period around 110 million years ago and is regarded as among the largest pterosaurs to have existed in the Southern Hemisphere, with a wingspan of over 8 meters. Its name translates to "Keel Jaw", in reference to the enlarged crests on its jaw, which the dinosaur uses to retain balance when diving into water to catch fish.',
    era: 'Early Cretaceous',
    family: 'Ornithocheiridae',
    diet: 'Piscivore',
    attack: 45,
    defense: 20,
    appeal: 216,
    likes: ['None'],
    dislikes: ['Tapejara'],
  },
  {
    dinoName: 'Dimorphodon',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/e/e2/Dimorphodon_database_image_from_Evolution_2.png/revision/latest?cb=20211209152702',
    rarity: 'Common',
    type: 'Flying reptiles',
    price: 92500,
    description:
      'Dimorphodon was later cloned by InGen for Jurassic World on Isla Nublar, where it lived alongside Pteranodon in the Jurassic World Aviary. During the 2015 incident, the Aviary was compromised by the rampaging Indominus rex, allowing the pterosaur population to escape and attack the park guests. After the incident, all surviving Dimorphodon were left to roam wild across the island. In 2016, they were using the Lookout Point of the Gondola Lift as their nesting ground, where they were encountered by the survivors of Camp Cretaceous, Jurassic World resident summer camp.',
    era: 'Early Jurassic',
    family: 'Dimorphodontidae',
    diet: 'Piscivore',
    attack: 20,
    defense: 14,
    appeal: 50,
    likes: ['Quetzalcoatlus'],
    dislikes: ['Indominus rex', 'Indoraptor', 'Scorpios rex'],
  },
  {
    dinoName: 'Quetzalcoatlus',
    image:
      'https://image-service.zaonce.net/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiIyMDIyLTA2L3F1ZXR6YWxjb2F0bHVzXzY2MDM3LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzAwfX19',
    rarity: 'Legendary',
    type: 'Flying reptiles',
    price: 1250000,
    description:
      'Quetzalcoatlus was discovered through chance by Douglas A. Lawson in 1971 - while digging for sauropods at Big Bend National Park in Texas, Lawsons team unearthed a giant wing bone fossil. The bone was so large that there was much controversy over what animal the specimen belonged to, but Lawson was able to show comparisons to Pterodactyl that confirmed it was, in fact, a new and much larger genus. Quetzalcoatlus was among the largest pterosaurs ever known, with a wingspan of 9 to 12 m (30 to 40 ft) wide and weighing 70–250 kg (150–550 lb). Wingspans of 18.3 m (60 ft) were estimated, but have since been discredited. The flying habits of Quetzalcoatlus have been debated due to its large size, with some theorizing that it was a soaring animal while others say it was completely flightless. Recent studies have shown that it would be capable of boosting itself several feet into the air with its hind legs to gain the momentum necessary for downstrokes.',
    era: 'Late Cretaceous',
    family: 'Azhdarchidae',
    diet: 'Carnivore',
    attack: 180,
    defense: 95,
    appeal: 2400,
    likes: ['Dimorphodon', 'Cearadactylus', 'Tapejara', 'Barbaridactylus'],
    dislikes: ['None'],
  },
  {
    dinoName: 'Tapejara',
    image:
      'https://static.wikia.nocookie.net/jurassicworld-evolution/images/8/83/Tapejara_database_image_from_Evolution_2.png/revision/latest?cb=20211209152811',
    rarity: 'Common',
    type: 'Flying reptiles',
    price: 85000,
    description:
      'A rather small species of pterosaur native to Brazil with a unique appearance, Tapejara can be easily recognized by its massive crest on top of its head, which consisted of a semicircular crest over the snout and a bony prong or sail which extends back behind the head that measures a meter in length, helping it to attract mates. Its wingspan of around 4 meters makes it one of the smaller pterosaurs, while the name Tapejara translates to "Old Being".',
    era: 'Early Cretaceous',
    family: 'Tapejaridae',
    diet: 'Piscivore',
    attack: 24,
    defense: 16,
    appeal: 120,
    likes: ['Quetzalcoatlus'],
    dislikes: ['Tropeognathus'],
  },
  {
    dinoName: 'Mosasaurus',
    image:
      'https://static.wikia.nocookie.net/jurassicpark/images/8/8d/Mosasaurus_%282%29.png/revision/latest?cb=20190622142157',
    rarity: 'Legendary',
    type: 'Marine reptiles',
    price: 1300000,
    description:
      'he largest member and namesake of its family (its name translates to "Lizard of the Meuse River", in reference to the location of its discovery), Mosasaurus is one of the largest marine reptiles in history, growing up to nearly 18 meters in length, and lived in the Late Cretaceous period from 82 to 65 million years ago in the Atlantic Ocean. Mosasaurus rows of sharp teeth, powerful paddle-like limbs and excellent vision make it an efficient predator, feeding on fish, cephalopods and other marine reptiles. Mosasaurus also has crocodilian-like osteoderms running down its back and tail. Mosasaurus greatly resembles Tylosaurus, but had a more robust physique. The base genome of Mosasaurus are grayish-blue with a creamy underbelly.',
    era: 'Late Cretaceous',
    family: 'Mosasauridae',
    diet: 'Piscivore',
    attack: 130,
    defense: 34,
    appeal: 2500,
    likes: ['Marine (Small)'],
    dislikes: ['Marine (Large)'],
  },
]
